"""initial

Revision ID: 05521effa749
Revises: 
Create Date: 2026-03-28 13:28:33.211815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05521effa749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('hex', sa.String(length=7), nullable=False),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('green', sa.Integer(), nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('hue', sa.Integer(), nullable=False),
    sa.Column('saturate', sa.Integer(), nullable=False),
    sa.Column('lightness', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colors'))
    )
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotions')),
    sa.UniqueConstraint('name', name=op.f('uq_emotions_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole'), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('emotion_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], name=op.f('fk_emotion_colors_color_id_colors')),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], name=op.f('fk_emotion_colors_emotion_id_emotions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emotion_colors'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_number', sa.Integer(), nullable=False),
    sa.Column('emotion_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('harmony_type', sa.Enum('analogous', 'complementary', 'triadic', 'monochromatic', name='harmonytype'), nullable=True),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotions.id'], name=op.f('fk_tasks_emotion_id_emotions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('score_emotion', sa.Integer(), nullable=False),
    sa.Column('score_harmony', sa.Integer(), nullable=False),
    sa.Column('score_contrast', sa.Integer(), nullable=True),
    sa.Column('score_colorblind', sa.Integer(), nullable=True),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('harmony_used', sa.Enum('analogous', 'complementary', 'triadic', 'monochromatic', name='harmonytype'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_results_task_id_tasks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_results_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('tasks')
    op.drop_table('emotion_colors')
    op.drop_table('users')
    op.drop_table('emotions')
    op.drop_table('colors')
    # ### end Alembic commands ###
