"""use case, float hsl

Revision ID: 8bdddd337417
Revises: 9e6f3d60a0ff
Create Date: 2026-04-02 22:27:43.291222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8bdddd337417'
down_revision = '9e6f3d60a0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_case', sa.Text(), nullable=True))
        batch_op.alter_column('hue',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('saturate',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('lightness',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colors', schema=None) as batch_op:
        batch_op.alter_column('lightness',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('saturate',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('hue',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('use_case')

    # ### end Alembic commands ###
